# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Matt @ Work'
email: mattm@theothermattm.com
description: >- # this means to ignore newlines until "baseurl:"
  Clean Code + Coffee == Happy Developers 
url: 'https://theothermattm.github.io/'
github_username:  theothermattm
linkedin_username: theothermattm
mastodon_url: https://mastodon.social/@theothermattm
google_analytics: G-C06BSKXDG4

# for github pages
# remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
# for local testing
theme: jekyll-theme-clean-blog

baseurl: ''

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

# console theme vars
header_pages:
  - about.md
  - portfolio.md

paginate:           10
paginate_path:      "/posts/page:num/"
page_exerpts: true

defaults:
 - 
  scope:
     path: ""
  values: 
     background: '/img/clean/bg-post.jpg'
     author: 'Matt'

jekyll-archives:
  enabled: ['categories', 'tags']
  layout: archive
  permalinks:
    tag: '/posts/tag/:name/'
    category: '/posts/category/:name/'

# console theme vars

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - LICENSE.md
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
